# Pick meat from microwave: global DP3 single cam (all agents use one specified pointcloud, shared UNet)
name: pick_meat_from_microwave_3d_global_single_cam
agent_num: 3

# Same as local_single_cam: [1,1,1] -> all use pointcloud_1
policy:
  pointcloud_source_id: 0

point_shape: &point_shape [512, 3]
action_shape: &action_shape [8]

shape_meta: &shape_meta
  # acceptable types: rgb, point_cloud, low_dim
  obs:
    pointcloud:
      shape: *point_shape
      type: point_cloud
    state:
      shape: *action_shape
      type: low_dim
  action:
    shape: *action_shape

dataset:
  _target_: dataset.dataset3d.Dataset3D
  dataset_path: data/pick_meat_from_microwave_pointcloud.h5
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  input_meta:
    obs:
      pointcloud_0: *point_shape
      pointcloud_1: *point_shape
      pointcloud_2: *point_shape
      state_0: *action_shape
      state_1: *action_shape
      state_2: *action_shape
    action_0: *action_shape
    action_1: *action_shape
    action_2: *action_shape
  seperate_action: True
  only_xyz: True
  use_mem: True
