from .pick_meat import solve as solvePickMeat
from .camera_alignment import solve as solveCameraAlignment
from .stack_cube import solve as solveStackCube
from .strike_cube import solve as solveStrikeCube
from .place_food import solve as solvePlaceFood
from .pass_shoe import solve as solvePassShoe
from .two_robots_stack_cube import solve as solveTwoRobotsStackCube
from .two_robots_stack_cube_active import solve as solveTwoRobotsStackCubeActive
from .three_robots_stack_cube import solve as solveThreeRobotsStackCube
from .lift_barrier import solve as solveLiftBarrier
from .take_photo import solve as solveTakePhoto
from .long_pipeline_delivery import solve as solveLongPipelineDelivery
from .stack_cube_active import solve as solveStackCubeActive
from .place_shoe import solve as solvePlaceShoe
from .pick_meat_from_pot import solve as solvePickMeatFromPot
from .pick_cube_from_cabinet import solve as solvePickCubeFromCabinet
from .pick_meat_from_microwave import solve as solvePickMeatFromMicrowave
from .pick_meat_from_microwave_A import solve as solvePickMeatFromMicrowaveA
from .pick_meat_from_microwave_B import solve as solvePickMeatFromMicrowaveB
from .pick_meat_from_microwave_C import solve as solvePickMeatFromMicrowaveC
from .place_cube_on_cart import solve as solvePlaceCubeOnCart
from .pick_meat_from_microwave_robocasa import solve as solvePickMeatFromMicrowaveRobocasa