# Two robots task: left-to-right handover with active perception.
task_name: TwoRobotsHandoverActiveA
task:
  direction: left_to_right
  cube_mass: 0.03
scene:
  name: Table
  primitives:
    - name: left_goal_region
      builder: mani_skill.utils.building.actors.build_red_white_target
      params:
        radius: 0.09
        thickness: 0.00005
        name: left_goal_region
        add_collision: False
        body_type: kinematic
        initial_pose:
          p: [0.0, -0.28, 0.001]
      pos:
        ppos:
          p: [0.0, -0.28, 0.001]
          q: [0., 1.5707963268, 0.]
        qpos: [0., 0.70710678, 0., 0.70710678]
        randp_scale: [0., 0., 0.]
        randq_scale: [0., 0., 0., 0.]

    - name: right_goal_region
      builder: mani_skill.utils.building.actors.build_red_white_target
      params:
        radius: 0.09
        thickness: 0.00005
        name: right_goal_region
        add_collision: False
        body_type: kinematic
        initial_pose:
          p: [0.0, 0.28, 0.001]
      pos:
        ppos:
          p: [0.0, 0.28, 0.001]
          q: [0., 1.5707963268, 0.]
        qpos: [0., 0.70710678, 0., 0.70710678]
        randp_scale: [0., 0., 0.]
        randq_scale: [0., 0., 0., 0.]

    - name: cube
      builder: mani_skill.utils.building.actors.build_cube
      params:
        half_size: 0.03
        color: [0.04705882, 0.16470588, 0.62745098, 1.]
        name: cube
        initial_pose:
          p: [0.0, -0.28, 0.03]
      pos:
        ppos:
          p: [0.0, -0.28, 0.03]
        qpos: [1., 0., 0., 0.]
        randp_scale: [0.04, 0.02, 0.]
        randq_scale: [0., 0., 0., 0.]
        random_quaternions: [1, 1, 0]
  assets:
    - name: table
      file_path: ${ASSET_DIR}/scenes/table/table.glb
      collision:
        type: box
        pos:
          p: [0, 0, 0.45982145]
          half_size: [3.0225, 1.51125, 0.45982145]
      pos:
        ppos:
          p: [-0.12, 0., -0.9196429]
          q: [0., 0., 1.5707963268]
        randp_scale: [0., 0., 0.]
        randq_scale: [0., 0., 0., 0.]
      scale: [4.375, 4.375, 1.75]
  env:
    floor_width: 100

agents:
  - robot_uid: panda_wristcam-0
    pos:
      ppos:
        p: [-0.35, -0.45, 0.]
        q: [0., 0., 0.]
      qpos: [-0.009814125, -0.19360411, 0.02991455, -1.6444968, 0.0058720573, 1.4378732, 0.78325164, 0.0, 0.0]
      randp_scale: [0., 0., 0.]
      randq_scale: [0., 0., 0., 0., 0., 0., 0., 0., 0.]
  - robot_uid: panda_wristcam-1
    pos:
      ppos:
        p: [-0.35, 0.45, 0.]
        q: [0., 0., 0.]
      qpos: [-0.0045072525, -0.45740202, 0.029070009, -1.9424388, 0.012210712, 1.5065452, 0.7861129, 0.0, 0.0]
      randq_scale: [0., 0., 0., 0., 0., 0., 0., 0., 0.]

cameras:
  sensor:
    - uid: head_camera_global
      pose:
        type: pose
        params: [[1.06061, 0.0726414, 0.571217], [0.00809935, -0.136369, 0.00111495, 0.990624]]
      width: 320
      height: 240
      fov: 1.5707963268
      near: 0.01
      far: 10
  human_render:
    - uid: render_camera
      pose:
        type: look_at
        params: [[1.4, 0.8, 0.75], [0., 0.0, 0.1]]
      width: 512
      height: 512
      fov: 1
      near: 0.01
      far: 100
